[package]
name = "pcs"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
binius_field = { version = "0.1.0", path = "../field" }
paste = "1.0.15"
rand.workspace = true
rayon.workspace = true
sha3 = "0.10.8"
concat-arrays = "0.1.2"